AddTunnelsSheet: Resolve missing primary constructor
If a configuration change occurs with the bottom sheet expanded, recreate
looks for an empty primary constructor to re-inflate fragments. In our case
the default constructor is not empty and thus throws this exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{me.msfjarvis.viscerion.debug/com.wireguard.android.activity.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.wireguard.android.ui.AddTunnelsSheet: could not find Fragment constructor

To counter the problem, we make the primary constructor empty and introduce a
secondary constructor to store the fragment instance. This is by no means perfect
but it will have to do for now. Open to suggestions for improving this to use the
more common FragmentClass.newInstance(args) paradigm.

Signed-off-by: Harsh Shandilya <msfjarvis@gmail.com>